name: "ACTION-ecs-service-poller"
description: "A polling mechanism that checks to see if the new service is up and ready. It also checks to see if it is using the newest revision of the task def."

inputs:
  service_name:
    description: "The name of the services"
    required: true
  cluster_name:
    description: "The name of the cluster"
    required: true
  region:
    description: "The region of the ECS cluster"
    required: false
    default: "us-west-2"
  max_retries:
    description: "The maximum number of retries to check the service status: default is 30"
    required: false
    default: "30"
  delay:
    description: "The delay between retries in miliseconds default is 60000 (60 seconds)"
    required: false
    default: "60000"

outputs:
  status:
    description: "The status of the service, either `running` or `failed`"

runs:
  using: "node20"
  main: "dist/index.js"
