name: Update Readme Labels

on:
  push:
    branches:
      - main
env:
  BUILD_ID: ${{ github.run_id }}
jobs:
  generate_slug:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Repo Vars
        id: shorten
        run: |
          BRANCH_SLUG=$(echo "${GITHUB_HEAD_REF:-$GITHUB_REF_NAME}" | sed 's/refs\/heads\///')
          echo "BRANCH_SLUG=$(echo ${BRANCH_SLUG})" >> $GITHUB_OUTPUT
          echo "REPO_NAME=$(echo ${GITHUB_REPOSITORY#*/})" >> $GITHUB_OUTPUT
    outputs:
      BRANCH_SLUG: ${{ steps.shorten.outputs.BRANCH_SLUG }}
      REPO_NAME: ${{ steps.shorten.outputs.REPO_NAME }}

  update-Readme:
    runs-on: ubuntu-latest
    needs: generate_slug
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check latest release and get badge URL
        uses: aliciousness/ACTION-latest-release-badge@v1.1.0
        id: check_release
        with:
          repo: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: debug
        run: echo "${{ steps.check_release.outputs.badge_url }}"

      - name: Get Last Commit Date
        id: last_commit
        run: |
          LAST_COMMIT=$(git log -1 --format=%cd --date=short)
          echo "LAST_COMMIT_DATE=$LAST_COMMIT" >> $GITHUB_ENV

      - name: Update Readme
        run: |
          # Latest Release badge
          sed -i "s|\[!\[Latest Release\](.*)](https://github.com/aliciousness/ACTION-latest-release-badge/releases)|[![Latest Release](${{ steps.check_release.outputs.badge_url }})](https://github.com/aliciousness/ACTION-latest-release-badge/releases)|" Readme.md

      - name: Set up the branch for pushing
        run: |
          git checkout ${{ needs.generate_slug.outputs.BRANCH_SLUG }}
          git pull origin ${{ needs.generate_slug.outputs.BRANCH_SLUG }}  # Ensure it's up to date

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add Readme.md
          git commit -m "Update Readme labels"
          git push origin ${{ needs.generate_slug.outputs.BRANCH_SLUG }}
